//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTrackerBase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpicIssueMapper
    {
        public int EpicMapperId { get; set; }
        public int EpicIssueId { get; set; }
        public int LinkedIssueId { get; set; }
        public int LinkedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual IssueDetail IssueDetail { get; set; }
        public virtual IssueDetail IssueDetail1 { get; set; }
        public virtual User User { get; set; }
    }
}
