//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTrackerBase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IssueDetail()
        {
            this.EpicIssueMappers = new HashSet<EpicIssueMapper>();
            this.EpicIssueMappers1 = new HashSet<EpicIssueMapper>();
            this.IssuesCustomFieldValueMappers = new HashSet<IssuesCustomFieldValueMapper>();
        }
    
        public int IssueId { get; set; }
        public string TaskId { get; set; }
        public string Title { get; set; }
        public int ComponentId { get; set; }
        public int IssueTypeId { get; set; }
        public int PriorityId { get; set; }
        public string Description { get; set; }
        public int StatusId { get; set; }
        public int EngineerId { get; set; }
        public int AssigneeId { get; set; }
        public int ReportingPersionId { get; set; }
        public Nullable<int> ReleaseVerionId { get; set; }
        public Nullable<decimal> StoryPoints { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ResolutionId { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Component Component { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EpicIssueMapper> EpicIssueMappers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EpicIssueMapper> EpicIssueMappers1 { get; set; }
        public virtual IssueType IssueType { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual ReleaseVersion ReleaseVersion { get; set; }
        public virtual Resolution Resolution { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual User User4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssuesCustomFieldValueMapper> IssuesCustomFieldValueMappers { get; set; }
    }
}
