//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTrackerBase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectPermissionMapper
    {
        public int MapperId { get; set; }
        public int ProjectId { get; set; }
        public int UserId { get; set; }
        public int ProjectRoleId { get; set; }
        public int ModifedBy { get; set; }
        public System.DateTime ModifedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ProjectRole ProjectRole { get; set; }
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
