//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTrackerBase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseVersionProjectMapper
    {
        public int MapperId { get; set; }
        public int ReleaseVersionId { get; set; }
        public int ProjectId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ReleaseVersion ReleaseVersion { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
