//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTrackerBase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowTransaction
    {
        public int TransactionId { get; set; }
        public int WorkfFowMapperId { get; set; }
        public int StatusId { get; set; }
        public int SortOrder { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual WorkFlowStatu WorkFlowStatu { get; set; }
    }
}
